function jsDoc(value) {
  return value.replace(/\*\//g, "* /");
}

function stringify(value) {
  return JSON.stringify(value, null, 2);
}

function policyMatrix(graph) {
  return graph.capabilities.map((capability) => ({
    capability: capability.name,
    purpose: capability.sections.purpose || [],
    reads: capability.reads,
    disclosureModes: capability.disclosureModes,
    forbiddenDisclosure: capability.forbiddenDisclosure,
    decisions: capability.policy.decisions,
    approval: capability.hasApproval || capability.policy.decisions.some((decision) => decision.kind === "require_approval"),
    broker: capability.sections.broker || [],
    audit: capability.auditEvents,
  }));
}

function capabilitiesTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    purpose: capability.sections.purpose || [],
    reads: capability.reads,
    disclosureModes: capability.disclosureModes,
    forbiddenDisclosure: capability.forbiddenDisclosure,
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomCapabilities = ${stringify(data)} as const;

export type AxiomCapabilityKey = (typeof axiomCapabilities)[number]["key"];
`;
}

function dataClassesTs(graph) {
  const data = graph.dataClasses.map((dataClass) => ({
    key: dataClass.name,
    sensitivity: dataClass.sensitivity,
    allowedDisclosure: dataClass.allowedDisclosure,
    defaultApproval: dataClass.defaultApproval,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomDataClasses = ${stringify(data)} as const;

export type AxiomDataClassKey = (typeof axiomDataClasses)[number]["key"];
`;
}

function auditEventsTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    capability: capability.name,
    audit: capability.auditEvents,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomAuditObligations = ${stringify(data)} as const;
`;
}

function brokerContractFor(capability) {
  const lines = capability.sections.broker || [];
  return {
    capability: capability.name,
    mayDecrypt: lines.map((line) => /^may_decrypt\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
    mayRead: lines.map((line) => /^may_read\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
    mayReturn: lines.map((line) => /^may_return\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
    mayExecute: lines.map((line) => /^may_execute\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
    forbidden: lines.map((line) => /^forbidden\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
  };
}

function approvalContractFor(capability) {
  const lines = capability.sections.approval || [];
  const bindLine = lines.map((line) => /^binds\s+(.+)$/.exec(line)?.[1]).find(Boolean);
  return {
    capability: capability.name,
    required: capability.hasApproval || capability.policy.decisions.some((decision) => decision.kind === "require_approval"),
    modes: lines.filter((line) => !line.startsWith("binds ")),
    binds: bindLine ? bindLine.split(",").map((item) => item.trim()).filter(Boolean) : [],
  };
}

function auditContractFor(capability) {
  const lines = capability.sections.audit || [];
  return {
    capability: capability.name,
    events: lines.filter((line) => !line.startsWith("never log ")),
    forbiddenLogFields: lines.map((line) => /^never log\s+(.+)$/.exec(line)?.[1]).filter(Boolean),
  };
}

function brokerContractsTs(graph) {
  const data = graph.capabilities.map(brokerContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomBrokerContracts = ${stringify(data)} as const;
`;
}

function approvalContractsTs(graph) {
  const data = graph.capabilities.map(approvalContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomApprovalContracts = ${stringify(data)} as const;
`;
}

function auditContractsTs(graph) {
  const data = graph.capabilities.map(auditContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomAuditContracts = ${stringify(data)} as const;
`;
}

function brokerContractsMjs(graph) {
  const data = graph.capabilities.map(brokerContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomBrokerContracts = ${stringify(data)};

export function brokerContractFor(capabilityKey) {
  return axiomBrokerContracts.find((item) => item.capability === capabilityKey) || null;
}
`;
}

function approvalContractsMjs(graph) {
  const data = graph.capabilities.map(approvalContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomApprovalContracts = ${stringify(data)};

export function approvalContractFor(capabilityKey) {
  return axiomApprovalContracts.find((item) => item.capability === capabilityKey) || null;
}

export function validateApprovalPayload(capabilityKey, approval = {}) {
  const contract = approvalContractFor(capabilityKey);
  if (!contract || !contract.required) return { ok: true, missing: [] };

  const missing = contract.binds.filter((field) => approval[field] === undefined || approval[field] === null || approval[field] === "");
  return { ok: missing.length === 0, missing, contract };
}
`;
}

function auditContractsMjs(graph) {
  const data = graph.capabilities.map(auditContractFor);
  return `/* Generated by Axiom. Do not edit directly. */
export const axiomAuditContracts = ${stringify(data)};

export function auditContractFor(capabilityKey) {
  return axiomAuditContracts.find((item) => item.capability === capabilityKey) || null;
}

export function createAuditEvent(capabilityKey, payload = {}) {
  const contract = auditContractFor(capabilityKey);
  if (!contract) {
    throw new Error(\`Unknown Axiom audit capability: \${capabilityKey}\`);
  }

  const forbidden = contract.forbiddenLogFields.filter((field) => Object.prototype.hasOwnProperty.call(payload, field));
  if (forbidden.length) {
    throw new Error(\`Axiom audit payload for \${capabilityKey} includes forbidden field(s): \${forbidden.join(", ")}\`);
  }

  return {
    capability: capabilityKey,
    events: contract.events,
    payload,
  };
}
`;
}

function pythonData(value) {
  if (value === null || value === undefined) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    return `[\n${value.map((item) => `  ${indentPython(pythonData(item))}`).join(",\n")}\n]`;
  }
  const entries = Object.entries(value);
  if (!entries.length) return "{}";
  return `{\n${entries.map(([key, item]) => `  ${JSON.stringify(key)}: ${indentPython(pythonData(item))}`).join(",\n")}\n}`;
}

function indentPython(value) {
  return value.replace(/\n/g, "\n  ");
}

function modelsPy(graph) {
  const capabilities = graph.capabilities.map((capability) => ({
    key: capability.name,
    purpose: capability.sections.purpose || [],
    reads: capability.reads,
    disclosure_modes: capability.disclosureModes,
    forbidden_disclosure: capability.forbiddenDisclosure,
    decisions: capability.policy.decisions.map((decision) => decision.kind),
  }));
  const dataClasses = graph.dataClasses.map((dataClass) => ({
    key: dataClass.name,
    sensitivity: dataClass.sensitivity,
    allowed_disclosure: dataClass.allowedDisclosure,
    default_approval: dataClass.defaultApproval,
  }));

  return `# Generated by Axiom. Do not edit directly.
from typing import Any, Literal

from pydantic import BaseModel, Field


AxiomDecision = Literal["allow", "deny", "require_approval"]


class AxiomCapability(BaseModel):
    key: str
    purpose: list[str] = Field(default_factory=list)
    reads: list[str] = Field(default_factory=list)
    disclosure_modes: list[str] = Field(default_factory=list)
    forbidden_disclosure: list[str] = Field(default_factory=list)
    decisions: list[AxiomDecision] = Field(default_factory=list)


class AxiomDataClass(BaseModel):
    key: str
    sensitivity: str | None = None
    allowed_disclosure: list[str] = Field(default_factory=list)
    default_approval: list[str] = Field(default_factory=list)


class AxiomPolicyResult(BaseModel):
    capability: str
    decision: AxiomDecision
    reasons: list[str] = Field(default_factory=list)
    matched_rule: dict[str, Any] | None = None
    required_approval: dict[str, Any] | None = None


AXIOM_CAPABILITIES: list[AxiomCapability] = [
${capabilities.map((item) => `    AxiomCapability(**${pythonData(item).replace(/\n/g, "\n    ")}),`).join("\n")}
]

AXIOM_DATA_CLASSES: list[AxiomDataClass] = [
${dataClasses.map((item) => `    AxiomDataClass(**${pythonData(item).replace(/\n/g, "\n    ")}),`).join("\n")}
]
`;
}

function auditContractsPy(graph) {
  const data = graph.capabilities.map((capability) => ({
    capability: capability.name,
    audit: capability.auditEvents,
  }));

  return `# Generated by Axiom. Do not edit directly.
from dataclasses import dataclass


@dataclass(frozen=True)
class AxiomAuditObligation:
    capability: str
    audit: list[str]


AXIOM_AUDIT_OBLIGATIONS: list[AxiomAuditObligation] = [
${data.map((item) => `    AxiomAuditObligation(**${pythonData(item).replace(/\n/g, "\n    ")}),`).join("\n")}
]


def audit_obligations_for(capability: str) -> list[str]:
    for obligation in AXIOM_AUDIT_OBLIGATIONS:
        if obligation.capability == capability:
            return obligation.audit
    return []
`;
}

function policyEvaluatorPy(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    approval: capability.sections.approval || [],
    decisions: capability.policy.decisions,
  }));

  return `# Generated by Axiom. Do not edit directly.
import re
from typing import Any, Literal, TypedDict


AxiomDecision = Literal["allow", "deny", "require_approval"]


class AxiomPolicyResult(TypedDict):
    capability: str
    decision: AxiomDecision
    reasons: list[str]
    matched_rule: dict[str, Any] | None
    required_approval: dict[str, Any] | None


AXIOM_POLICY_TABLE: list[dict[str, Any]] = ${pythonData(data)}


def _normalize_condition(condition: str) -> str:
    return re.sub(r"^(and|or)\\s+", "", condition).strip()


def _condition_key(condition: str) -> str:
    normalized = _normalize_condition(condition)
    normalized = re.sub(r"^not\\s+", "", normalized)
    return re.sub(r"\\s+", "_", normalized)


def _condition_matches(condition: str, facts: dict[str, Any]) -> bool:
    normalized = _normalize_condition(condition)
    negated = normalized.startswith("not ")
    key = _condition_key(normalized)
    value = facts.get(key) is True or facts.get(key) == "true"
    return not value if negated else value


def _decision_matches(decision: dict[str, Any], facts: dict[str, Any]) -> tuple[bool, list[str]]:
    conditions = decision.get("conditions", [])
    if not conditions:
        return False, []

    matched = _condition_matches(conditions[0], facts)
    reasons = [_condition_key(conditions[0])] if matched else []

    for condition in conditions[1:]:
        operator = "or" if condition.startswith("or ") else "and"
        next_match = _condition_matches(condition, facts)
        if operator == "and":
            matched = matched and next_match
        else:
            matched = matched or next_match
        if next_match:
            reasons.append(_condition_key(condition))

    return matched, list(dict.fromkeys(reasons))


def evaluate_axiom_policy(capability_key: str, facts: dict[str, Any] | None = None) -> AxiomPolicyResult:
    facts = facts or {}
    contract = next((item for item in AXIOM_POLICY_TABLE if item["key"] == capability_key), None)
    if contract is None:
        return {
            "capability": capability_key,
            "decision": "deny",
            "reasons": ["unknown_capability"],
            "matched_rule": None,
            "required_approval": None,
        }

    for decision_kind in ["deny", "require_approval", "allow"]:
        for decision in [item for item in contract["decisions"] if item["kind"] == decision_kind]:
            matched, reasons = _decision_matches(decision, facts)
            if matched:
                return {
                    "capability": contract["key"],
                    "decision": decision["kind"],
                    "reasons": reasons,
                    "matched_rule": decision,
                    "required_approval": (
                        {"capability": contract["key"], "binds": contract["approval"]}
                        if decision["kind"] == "require_approval"
                        else None
                    ),
                }

    return {
        "capability": contract["key"],
        "decision": "deny",
        "reasons": ["no_policy_rule_matched"],
        "matched_rule": None,
        "required_approval": None,
    }
`;
}

function policyEvaluatorTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    approval: capability.sections.approval || [],
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomPolicyTable = ${stringify(data)} as const;

export type AxiomDecision = "allow" | "deny" | "require_approval";

export type AxiomPolicyResult = {
  capability: string;
  decision: AxiomDecision;
  reasons: string[];
  matchedRule: unknown;
  requiredApproval: null | {
    capability: string;
    binds: readonly string[];
  };
};

function normalizeCondition(condition: string) {
  return condition.replace(/^(and|or)\\s+/, "").trim();
}

function conditionKey(condition: string) {
  return normalizeCondition(condition)
    .replace(/^not\\s+/, "")
    .replace(/\\s+/g, "_");
}

function conditionMatches(condition: string, facts: Record<string, unknown>) {
  const normalized = normalizeCondition(condition);
  const negated = normalized.startsWith("not ");
  const key = conditionKey(normalized);
  const value = facts[key] === true || facts[key] === "true";
  return negated ? !value : value;
}

function decisionMatches(decision: { conditions: readonly string[] }, facts: Record<string, unknown>) {
  if (!decision.conditions.length) return { matched: false, reasons: [] as string[] };

  let matched = conditionMatches(decision.conditions[0], facts);
  const reasons = matched ? [conditionKey(decision.conditions[0])] : [];

  for (const condition of decision.conditions.slice(1)) {
    const operator = condition.startsWith("or ") ? "or" : "and";
    const next = conditionMatches(condition, facts);
    if (operator === "and") {
      matched = matched && next;
    } else {
      matched = matched || next;
    }
    if (next) reasons.push(conditionKey(condition));
  }

  return { matched, reasons: [...new Set(reasons)] };
}

export function evaluateAxiomPolicy(capabilityKey: string, facts: Record<string, unknown>): AxiomPolicyResult {
  const contract = axiomPolicyTable.find((item) => item.key === capabilityKey);
  if (!contract) {
    return {
      capability: capabilityKey,
      decision: "deny",
      reasons: ["unknown_capability"],
      matchedRule: null,
      requiredApproval: null,
    };
  }

  for (const decisionKind of ["deny", "require_approval", "allow"] as const) {
    for (const decision of contract.decisions.filter((item) => item.kind === decisionKind)) {
      const result = decisionMatches(decision, facts);
      if (result.matched) {
        return {
          capability: contract.key,
          decision: decision.kind,
          reasons: result.reasons,
          matchedRule: decision,
          requiredApproval:
            decision.kind === "require_approval"
              ? { capability: contract.key, binds: contract.approval }
              : null,
        };
      }
    }
  }

  return {
    capability: contract.key,
    decision: "deny",
    reasons: ["no_policy_rule_matched"],
    matchedRule: null,
    requiredApproval: null,
  };
}
`;
}

function policyEvaluatorMjs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    approval: capability.sections.approval || [],
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomPolicyTable = ${stringify(data)};

function normalizeCondition(condition) {
  return condition.replace(/^(and|or)\\s+/, "").trim();
}

function conditionKey(condition) {
  return normalizeCondition(condition)
    .replace(/^not\\s+/, "")
    .replace(/\\s+/g, "_");
}

function conditionMatches(condition, facts) {
  const normalized = normalizeCondition(condition);
  const negated = normalized.startsWith("not ");
  const key = conditionKey(normalized);
  const value = facts[key] === true || facts[key] === "true";
  return negated ? !value : value;
}

function decisionMatches(decision, facts) {
  if (!decision.conditions.length) return { matched: false, reasons: [] };

  let matched = conditionMatches(decision.conditions[0], facts);
  const reasons = matched ? [conditionKey(decision.conditions[0])] : [];

  for (const condition of decision.conditions.slice(1)) {
    const operator = condition.startsWith("or ") ? "or" : "and";
    const next = conditionMatches(condition, facts);
    if (operator === "and") {
      matched = matched && next;
    } else {
      matched = matched || next;
    }
    if (next) reasons.push(conditionKey(condition));
  }

  return { matched, reasons: [...new Set(reasons)] };
}

export function evaluateAxiomPolicy(capabilityKey, facts = {}) {
  const contract = axiomPolicyTable.find((item) => item.key === capabilityKey);
  if (!contract) {
    return {
      capability: capabilityKey,
      decision: "deny",
      reasons: ["unknown_capability"],
      matchedRule: null,
      requiredApproval: null,
    };
  }

  for (const decisionKind of ["deny", "require_approval", "allow"]) {
    for (const decision of contract.decisions.filter((item) => item.kind === decisionKind)) {
      const result = decisionMatches(decision, facts);
      if (result.matched) {
        return {
          capability: contract.key,
          decision: decision.kind,
          reasons: result.reasons,
          matchedRule: decision,
          requiredApproval:
            decision.kind === "require_approval"
              ? { capability: contract.key, binds: contract.approval }
              : null,
        };
      }
    }
  }

  return {
    capability: contract.key,
    decision: "deny",
    reasons: ["no_policy_rule_matched"],
    matchedRule: null,
    requiredApproval: null,
  };
}
`;
}

function runtimeGuardsTs(graph) {
  return `/* Generated by Axiom. Do not edit directly. */
import { axiomCapabilities } from "./capabilities";

export type AxiomDecision = "allow" | "deny" | "require_approval";

export function getCapabilityContract(capabilityKey: string) {
  return axiomCapabilities.find((capability) => capability.key === capabilityKey);
}

export function assertKnownCapability(capabilityKey: string) {
  const contract = getCapabilityContract(capabilityKey);
  if (!contract) {
    throw new Error(\`Unknown Axiom capability: \${capabilityKey}\`);
  }
  return contract;
}

export function assertDisclosureMode(capabilityKey: string, disclosureMode: string) {
  const contract = assertKnownCapability(capabilityKey);
  if (!contract.disclosureModes.includes(disclosureMode as never)) {
    throw new Error(\`Disclosure mode \${disclosureMode} is not declared for \${capabilityKey}\`);
  }
}

export const axiomApp = ${JSON.stringify(graph.app?.name || "unknown")};
`;
}

function appSkeletonMjs(graph) {
  return `/* Generated by Axiom. Do not edit directly.
 * This is a minimal app skeleton, not a complete application.
 * Fill real broker execution, persistence, auth, and transport code outside generated files.
 */
import { validateApprovalPayload } from "./approval-contracts.mjs";
import { brokerContractFor } from "./broker-contracts.mjs";
import { createAuditEvent } from "./audit-contracts.mjs";
import { evaluateAxiomPolicy } from "./policy-evaluator.mjs";

export function assertBrokerResponse(capabilityKey, response = {}) {
  const contract = brokerContractFor(capabilityKey);
  if (!contract) {
    throw new Error(\`Unknown Axiom broker capability: \${capabilityKey}\`);
  }

  const forbidden = contract.forbidden.filter((field) => Object.prototype.hasOwnProperty.call(response, field));
  if (forbidden.length) {
    throw new Error(\`Axiom broker response for \${capabilityKey} includes forbidden field(s): \${forbidden.join(", ")}\`);
  }

  if (response.disclosureMode && !contract.mayReturn.includes(response.disclosureMode)) {
    throw new Error(\`Disclosure mode \${response.disclosureMode} is not declared as broker-returnable for \${capabilityKey}\`);
  }

  return response;
}

export function handleAxiomCapabilityRequest(request) {
  const capability = request.capability;
  const policy = evaluateAxiomPolicy(capability, request.facts || {});

  if (policy.decision === "deny") {
    return {
      status: "denied",
      policy,
    };
  }

  if (policy.decision === "require_approval") {
    const approval = validateApprovalPayload(capability, request.approval || {});
    if (!approval.ok || request.approval?.valid !== true) {
      return {
        status: "approval_required",
        policy,
        approval,
      };
    }
  }

  const brokerResponse = assertBrokerResponse(capability, request.brokerResponse || {});
  const auditEvent = createAuditEvent(capability, request.auditPayload || {});

  return {
    status: "ok",
    policy,
    brokerResponse,
    auditEvent,
  };
}

export const axiomGeneratedAppSkeleton = ${JSON.stringify(graph.app?.name || "unknown")};
`;
}

function inputFieldsFor(capability) {
  return capability.sections.input || [];
}

function firstDecisionFact(decision) {
  const condition = decision?.conditions?.[0] || "";
  return condition.replace(/^(and|or)\s+/, "").replace(/^not\s+/, "").trim().replace(/\s+/g, "_");
}

function decisionFacts(decision) {
  return Object.fromEntries(
    (decision?.conditions || [])
      .map((condition) => firstDecisionFact({ conditions: [condition] }))
      .filter(Boolean)
      .map((fact) => [fact, true]),
  );
}

function routePathFor(capabilityName) {
  return `/axiom/${capabilityName.replace(/_/g, "-")}`;
}

function routeSpecs(graph) {
  return graph.capabilities.map((capability) => ({
    capability: capability.name,
    method: "POST",
    path: routePathFor(capability.name),
    input: inputFieldsFor(capability),
    approvalRequired: capability.hasApproval || capability.policy.decisions.some((decision) => decision.kind === "require_approval"),
    broker: brokerContractFor(capability),
    audit: auditContractFor(capability),
  }));
}

function routeSkeletonMjs(graph) {
  return `/* Generated by Axiom. Do not edit directly.
 * Plain Node route skeleton. Bind these handlers to Express, Fastify, Next.js,
 * Hono, or another HTTP framework in hand-written adapter code.
 */
import { validateApprovalPayload } from "./approval-contracts.mjs";
import { createAuditEvent } from "./audit-contracts.mjs";
import { assertBrokerResponse } from "./app-skeleton.mjs";
import { evaluateAxiomPolicy } from "./policy-evaluator.mjs";

export const axiomRouteSpecs = ${stringify(routeSpecs(graph))};

export function routeSpecFor(capabilityKey) {
  return axiomRouteSpecs.find((item) => item.capability === capabilityKey) || null;
}

export async function handleAxiomRoute(capabilityKey, request = {}, dependencies = {}) {
  const spec = routeSpecFor(capabilityKey);
  if (!spec) {
    return {
      status: 404,
      body: { status: "unknown_capability", capability: capabilityKey },
    };
  }

  if (dependencies.authorize) {
    const authorized = await dependencies.authorize({ capability: capabilityKey, request, spec });
    if (!authorized) {
      return {
        status: 401,
        body: { status: "unauthorized", capability: capabilityKey },
      };
    }
  }

  const policy = evaluateAxiomPolicy(capabilityKey, request.facts || {});
  if (policy.decision === "deny") {
    return {
      status: 403,
      body: { status: "denied", policy },
    };
  }

  if (policy.decision === "require_approval") {
    const approval = validateApprovalPayload(capabilityKey, request.approval || {});
    if (!approval.ok || request.approval?.valid !== true) {
      return {
        status: 409,
        body: { status: "approval_required", policy, approval },
      };
    }
  }

  if (!dependencies.executeBroker) {
    throw new Error(\`Manual broker implementation required for \${capabilityKey}\`);
  }

  const brokerResponse = assertBrokerResponse(
    capabilityKey,
    await dependencies.executeBroker({ capability: capabilityKey, request, policy, spec }),
  );
  const auditEvent = createAuditEvent(capabilityKey, request.auditPayload || {});

  if (dependencies.writeAudit) {
    await dependencies.writeAudit(auditEvent);
  }

  return {
    status: 200,
    body: { status: "ok", policy, brokerResponse, auditEvent },
  };
}
`;
}

function generatedAppSkeletonTestMjs(graph) {
  const cases = graph.capabilities
    .map((capability) => {
      const broker = brokerContractFor(capability);
      const approval = approvalContractFor(capability);
      const audit = auditContractFor(capability);
      const requireApproval = capability.policy.decisions.find((decision) => decision.kind === "require_approval");
      return {
        capability: capability.name,
        forbiddenBrokerField: broker.forbidden[0] || null,
        forbiddenAuditField: audit.forbiddenLogFields[0] || null,
        approvalBind: approval.binds[0] || null,
        requireApprovalFact: firstDecisionFact(requireApproval) || null,
      };
    })
    .filter((item) => item.forbiddenBrokerField || item.forbiddenAuditField || item.approvalBind || item.requireApprovalFact);

  return `/* Generated by Axiom. Do not edit directly. */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { createAuditEvent } from "./audit-contracts.mjs";
import { assertBrokerResponse, handleAxiomCapabilityRequest } from "./app-skeleton.mjs";
import { validateApprovalPayload } from "./approval-contracts.mjs";

const cases = ${stringify(cases)};

describe("Axiom generated app skeleton", () => {
  for (const item of cases) {
    if (item.forbiddenBrokerField) {
      it(\`\${item.capability} rejects forbidden broker response fields\`, () => {
        assert.throws(
          () => assertBrokerResponse(item.capability, { [item.forbiddenBrokerField]: "secret" }),
          /forbidden field/,
        );
      });
    }

    if (item.forbiddenAuditField) {
      it(\`\${item.capability} rejects forbidden audit payload fields\`, () => {
        assert.throws(
          () => createAuditEvent(item.capability, { [item.forbiddenAuditField]: "secret" }),
          /forbidden field/,
        );
      });
    }

    if (item.approvalBind) {
      it(\`\${item.capability} requires approval binding fields\`, () => {
        const result = validateApprovalPayload(item.capability, {});
        assert.equal(result.ok, false);
        assert.ok(result.missing.includes(item.approvalBind));
      });
    }

    if (item.requireApprovalFact) {
      it(\`\${item.capability} returns approval_required before approval is valid\`, () => {
        const result = handleAxiomCapabilityRequest({
          capability: item.capability,
          facts: { [item.requireApprovalFact]: true },
        });
        assert.equal(result.status, "approval_required");
      });
    }
  }
});
`;
}

function generatedRouteSkeletonTestMjs(graph) {
  const cases = graph.capabilities
    .map((capability) => {
      const broker = brokerContractFor(capability);
      const audit = auditContractFor(capability);
      const allow = capability.policy.decisions.find((decision) => decision.kind === "allow");
      const deny = capability.policy.decisions.find((decision) => decision.kind === "deny");
      const requireApproval = capability.policy.decisions.find((decision) => decision.kind === "require_approval");
      return {
        capability: capability.name,
        allowFacts: decisionFacts(allow),
        denyFact: firstDecisionFact(deny) || null,
        requireApprovalFact: firstDecisionFact(requireApproval) || null,
        approvalBind: approvalContractFor(capability).binds[0] || null,
        forbiddenBrokerField: broker.forbidden[0] || null,
        forbiddenAuditField: audit.forbiddenLogFields[0] || null,
      };
    })
    .filter(
      (item) =>
        item.denyFact ||
        item.requireApprovalFact ||
        item.approvalBind ||
        item.forbiddenBrokerField ||
        item.forbiddenAuditField,
    );

  return `/* Generated by Axiom. Do not edit directly. */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { handleAxiomRoute, routeSpecFor } from "./route-skeleton.mjs";

const cases = ${stringify(cases)};

function throwingBroker() {
  throw new Error("broker should not execute");
}

describe("Axiom generated route skeleton", () => {
  for (const item of cases) {
    it(\`\${item.capability} exposes a route spec\`, () => {
      const spec = routeSpecFor(item.capability);
      assert.equal(spec.method, "POST");
      assert.match(spec.path, /^\\/axiom\\//);
    });

    if (item.denyFact) {
      it(\`\${item.capability} does not execute broker on deny\`, async () => {
        const result = await handleAxiomRoute(
          item.capability,
          { facts: { [item.denyFact]: true } },
          { executeBroker: throwingBroker },
        );
        assert.equal(result.status, 403);
        assert.equal(result.body.status, "denied");
      });
    }

    if (item.requireApprovalFact) {
      it(\`\${item.capability} does not execute broker before approval\`, async () => {
        const result = await handleAxiomRoute(
          item.capability,
          { facts: { [item.requireApprovalFact]: true } },
          { executeBroker: throwingBroker },
        );
        assert.equal(result.status, 409);
        assert.equal(result.body.status, "approval_required");
      });
    }

    if (item.approvalBind && item.requireApprovalFact) {
      it(\`\${item.capability} reports missing approval binding fields\`, async () => {
        const result = await handleAxiomRoute(
          item.capability,
          { facts: { [item.requireApprovalFact]: true }, approval: { valid: true } },
          { executeBroker: throwingBroker },
        );
        assert.equal(result.status, 409);
        assert.ok(result.body.approval.missing.includes(item.approvalBind));
      });
    }

    if (item.forbiddenBrokerField && Object.keys(item.allowFacts).length) {
      it(\`\${item.capability} rejects forbidden broker response fields\`, async () => {
        await assert.rejects(
          () =>
            handleAxiomRoute(
              item.capability,
              { facts: item.allowFacts },
              { executeBroker: async () => ({ [item.forbiddenBrokerField]: "secret" }) },
            ),
          /forbidden field/,
        );
      });
    }

    if (item.forbiddenAuditField && Object.keys(item.allowFacts).length) {
      it(\`\${item.capability} rejects forbidden audit payload fields\`, async () => {
        await assert.rejects(
          () =>
            handleAxiomRoute(
              item.capability,
              { facts: item.allowFacts, auditPayload: { [item.forbiddenAuditField]: "secret" } },
              { executeBroker: async () => ({}) },
            ),
          /forbidden field/,
        );
      });
    }
  }
});
`;
}

function reportMarkdown(graph, diagnostics, target) {
  const errors = diagnostics.filter((item) => item.severity === "error");
  const warnings = diagnostics.filter((item) => item.severity === "warning");
  const generatedContracts = policyMatrix(graph)
    .map(
      (item) => `### ${item.capability}

- Reads: ${item.reads.join(", ") || "none declared"}
- Disclosure: ${item.disclosureModes.join(", ") || "none declared"}
- Decisions: ${item.decisions.map((decision) => decision.kind).join(", ") || "none declared"}
- Approval path: ${item.approval ? "yes" : "no"}`,
    )
    .join("\n\n");

  return `# Axiom Verification Report

App: ${graph.app?.name || "unknown"}
Target: ${target}

## Summary

- Capabilities checked: ${graph.capabilities.length}
- Actors checked: ${graph.actors.length}
- Data classes checked: ${graph.dataClasses.length}
- Errors: ${errors.length}
- Warnings: ${warnings.length}

## Diagnostics

${diagnostics.length ? diagnostics.map((item) => `- **${item.severity.toUpperCase()}** ${item.message}${item.ref ? ` (${item.ref})` : ""}`).join("\n") : "- No diagnostics."}

## Generated Contracts

${generatedContracts}
`;
}

export function generateArtifacts(graph, diagnostics, { target }) {
  if (target === "python") {
    return [
      { path: "policy_matrix.json", contents: `${stringify(policyMatrix(graph))}\n` },
      { path: "models.py", contents: modelsPy(graph) },
      { path: "policy_evaluator.py", contents: policyEvaluatorPy(graph) },
      { path: "audit_contracts.py", contents: auditContractsPy(graph) },
      { path: "axiom_report.md", contents: reportMarkdown(graph, diagnostics, target) },
      {
        path: "README.md",
        contents: `# Generated Axiom Python Artifacts

These files were generated from an Axiom source graph.

- \`policy_matrix.json\`: capability, data, disclosure, policy, broker, and audit matrix
- \`models.py\`: Pydantic contract models for capabilities, data classes, and policy results
- \`policy_evaluator.py\`: generated deterministic policy evaluator
- \`audit_contracts.py\`: generated audit obligation stubs
- \`axiom_report.md\`: validation and generation report

Use these files as contracts for Python app code. Do not paste the full generated files into an LLM context window unless the user asks. Prefer importing \`evaluate_axiom_policy\` and summarizing the specific policy path being changed.

Regenerate with:

\`\`\`bash
axiom generate <file.ax> --target python --out generated-python
\`\`\`
`,
      },
    ];
  }

  if (target !== "typescript") {
    throw new Error(`Unsupported target ${target}. The MVP currently supports typescript and python.`);
  }

  return [
    { path: "policy-matrix.json", contents: `${stringify(policyMatrix(graph))}\n` },
    { path: "capabilities.ts", contents: capabilitiesTs(graph) },
    { path: "data-classes.ts", contents: dataClassesTs(graph) },
    { path: "audit-events.ts", contents: auditEventsTs(graph) },
    { path: "broker-contracts.ts", contents: brokerContractsTs(graph) },
    { path: "broker-contracts.mjs", contents: brokerContractsMjs(graph) },
    { path: "approval-contracts.ts", contents: approvalContractsTs(graph) },
    { path: "approval-contracts.mjs", contents: approvalContractsMjs(graph) },
    { path: "audit-contracts.ts", contents: auditContractsTs(graph) },
    { path: "audit-contracts.mjs", contents: auditContractsMjs(graph) },
    { path: "policy-evaluator.ts", contents: policyEvaluatorTs(graph) },
    { path: "policy-evaluator.mjs", contents: policyEvaluatorMjs(graph) },
    { path: "runtime-guards.ts", contents: runtimeGuardsTs(graph) },
    { path: "app-skeleton.mjs", contents: appSkeletonMjs(graph) },
    { path: "app-skeleton.test.mjs", contents: generatedAppSkeletonTestMjs(graph) },
    { path: "route-skeleton.mjs", contents: routeSkeletonMjs(graph) },
    { path: "route-skeleton.test.mjs", contents: generatedRouteSkeletonTestMjs(graph) },
    { path: "axiom-report.md", contents: reportMarkdown(graph, diagnostics, target) },
    {
      path: "README.md",
      contents: `# Generated Axiom Artifacts

These files were generated from an Axiom source graph.

- \`policy-matrix.json\`: capability, data, disclosure, policy, broker, and audit matrix
- \`capabilities.ts\`: generated capability contracts
- \`data-classes.ts\`: generated sensitive data class contracts
- \`audit-events.ts\`: generated audit obligations
- \`broker-contracts.ts\` / \`broker-contracts.mjs\`: generated broker boundary contracts
- \`approval-contracts.ts\` / \`approval-contracts.mjs\`: generated approval payload contracts
- \`audit-contracts.ts\` / \`audit-contracts.mjs\`: generated audit payload guards
- \`policy-evaluator.ts\`: generated deterministic policy evaluator
- \`policy-evaluator.mjs\`: generated deterministic policy evaluator for plain Node demos
- \`runtime-guards.ts\`: minimal TypeScript runtime assertions
- \`app-skeleton.mjs\`: minimal app skeleton that gates policy, approval, broker, and audit behavior
- \`app-skeleton.test.mjs\`: generated Node tests for the app skeleton guardrails
- \`route-skeleton.mjs\`: framework-neutral route skeleton with manual auth, broker, audit, persistence, and transport hooks
- \`route-skeleton.test.mjs\`: generated Node tests proving route guardrails before broker execution
- \`axiom-report.md\`: validation and generation report

Regenerate with:

\`\`\`bash
axiom generate <file.ax> --target typescript --out generated
\`\`\`
`,
    },
  ];
}
