function jsDoc(value) {
  return value.replace(/\*\//g, "* /");
}

function stringify(value) {
  return JSON.stringify(value, null, 2);
}

function policyMatrix(graph) {
  return graph.capabilities.map((capability) => ({
    capability: capability.name,
    purpose: capability.sections.purpose || [],
    reads: capability.reads,
    disclosureModes: capability.disclosureModes,
    forbiddenDisclosure: capability.forbiddenDisclosure,
    decisions: capability.policy.decisions,
    approval: capability.hasApproval || capability.policy.decisions.some((decision) => decision.kind === "require_approval"),
    broker: capability.sections.broker || [],
    audit: capability.auditEvents,
  }));
}

function capabilitiesTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    purpose: capability.sections.purpose || [],
    reads: capability.reads,
    disclosureModes: capability.disclosureModes,
    forbiddenDisclosure: capability.forbiddenDisclosure,
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomCapabilities = ${stringify(data)} as const;

export type AxiomCapabilityKey = (typeof axiomCapabilities)[number]["key"];
`;
}

function dataClassesTs(graph) {
  const data = graph.dataClasses.map((dataClass) => ({
    key: dataClass.name,
    sensitivity: dataClass.sensitivity,
    allowedDisclosure: dataClass.allowedDisclosure,
    defaultApproval: dataClass.defaultApproval,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomDataClasses = ${stringify(data)} as const;

export type AxiomDataClassKey = (typeof axiomDataClasses)[number]["key"];
`;
}

function auditEventsTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    capability: capability.name,
    audit: capability.auditEvents,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomAuditObligations = ${stringify(data)} as const;
`;
}

function policyEvaluatorTs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    approval: capability.sections.approval || [],
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomPolicyTable = ${stringify(data)} as const;

export type AxiomDecision = "allow" | "deny" | "require_approval";

export type AxiomPolicyResult = {
  capability: string;
  decision: AxiomDecision;
  reasons: string[];
  matchedRule: unknown;
  requiredApproval: null | {
    capability: string;
    binds: readonly string[];
  };
};

function normalizeCondition(condition: string) {
  return condition.replace(/^(and|or)\\s+/, "").trim();
}

function conditionKey(condition: string) {
  return normalizeCondition(condition)
    .replace(/^not\\s+/, "")
    .replace(/\\s+/g, "_");
}

function conditionMatches(condition: string, facts: Record<string, unknown>) {
  const normalized = normalizeCondition(condition);
  const negated = normalized.startsWith("not ");
  const key = conditionKey(normalized);
  const value = facts[key] === true || facts[key] === "true";
  return negated ? !value : value;
}

function decisionMatches(decision: { conditions: readonly string[] }, facts: Record<string, unknown>) {
  if (!decision.conditions.length) return { matched: false, reasons: [] as string[] };

  let matched = conditionMatches(decision.conditions[0], facts);
  const reasons = matched ? [conditionKey(decision.conditions[0])] : [];

  for (const condition of decision.conditions.slice(1)) {
    const operator = condition.startsWith("or ") ? "or" : "and";
    const next = conditionMatches(condition, facts);
    if (operator === "and") {
      matched = matched && next;
    } else {
      matched = matched || next;
    }
    if (next) reasons.push(conditionKey(condition));
  }

  return { matched, reasons: [...new Set(reasons)] };
}

export function evaluateAxiomPolicy(capabilityKey: string, facts: Record<string, unknown>): AxiomPolicyResult {
  const contract = axiomPolicyTable.find((item) => item.key === capabilityKey);
  if (!contract) {
    return {
      capability: capabilityKey,
      decision: "deny",
      reasons: ["unknown_capability"],
      matchedRule: null,
      requiredApproval: null,
    };
  }

  for (const decisionKind of ["deny", "require_approval", "allow"] as const) {
    for (const decision of contract.decisions.filter((item) => item.kind === decisionKind)) {
      const result = decisionMatches(decision, facts);
      if (result.matched) {
        return {
          capability: contract.key,
          decision: decision.kind,
          reasons: result.reasons,
          matchedRule: decision,
          requiredApproval:
            decision.kind === "require_approval"
              ? { capability: contract.key, binds: contract.approval }
              : null,
        };
      }
    }
  }

  return {
    capability: contract.key,
    decision: "deny",
    reasons: ["no_policy_rule_matched"],
    matchedRule: null,
    requiredApproval: null,
  };
}
`;
}

function policyEvaluatorMjs(graph) {
  const data = graph.capabilities.map((capability) => ({
    key: capability.name,
    approval: capability.sections.approval || [],
    decisions: capability.policy.decisions,
  }));

  return `/* Generated by Axiom. Do not edit directly. */
export const axiomPolicyTable = ${stringify(data)};

function normalizeCondition(condition) {
  return condition.replace(/^(and|or)\\s+/, "").trim();
}

function conditionKey(condition) {
  return normalizeCondition(condition)
    .replace(/^not\\s+/, "")
    .replace(/\\s+/g, "_");
}

function conditionMatches(condition, facts) {
  const normalized = normalizeCondition(condition);
  const negated = normalized.startsWith("not ");
  const key = conditionKey(normalized);
  const value = facts[key] === true || facts[key] === "true";
  return negated ? !value : value;
}

function decisionMatches(decision, facts) {
  if (!decision.conditions.length) return { matched: false, reasons: [] };

  let matched = conditionMatches(decision.conditions[0], facts);
  const reasons = matched ? [conditionKey(decision.conditions[0])] : [];

  for (const condition of decision.conditions.slice(1)) {
    const operator = condition.startsWith("or ") ? "or" : "and";
    const next = conditionMatches(condition, facts);
    if (operator === "and") {
      matched = matched && next;
    } else {
      matched = matched || next;
    }
    if (next) reasons.push(conditionKey(condition));
  }

  return { matched, reasons: [...new Set(reasons)] };
}

export function evaluateAxiomPolicy(capabilityKey, facts = {}) {
  const contract = axiomPolicyTable.find((item) => item.key === capabilityKey);
  if (!contract) {
    return {
      capability: capabilityKey,
      decision: "deny",
      reasons: ["unknown_capability"],
      matchedRule: null,
      requiredApproval: null,
    };
  }

  for (const decisionKind of ["deny", "require_approval", "allow"]) {
    for (const decision of contract.decisions.filter((item) => item.kind === decisionKind)) {
      const result = decisionMatches(decision, facts);
      if (result.matched) {
        return {
          capability: contract.key,
          decision: decision.kind,
          reasons: result.reasons,
          matchedRule: decision,
          requiredApproval:
            decision.kind === "require_approval"
              ? { capability: contract.key, binds: contract.approval }
              : null,
        };
      }
    }
  }

  return {
    capability: contract.key,
    decision: "deny",
    reasons: ["no_policy_rule_matched"],
    matchedRule: null,
    requiredApproval: null,
  };
}
`;
}

function runtimeGuardsTs(graph) {
  return `/* Generated by Axiom. Do not edit directly. */
import { axiomCapabilities } from "./capabilities";

export type AxiomDecision = "allow" | "deny" | "require_approval";

export function getCapabilityContract(capabilityKey: string) {
  return axiomCapabilities.find((capability) => capability.key === capabilityKey);
}

export function assertKnownCapability(capabilityKey: string) {
  const contract = getCapabilityContract(capabilityKey);
  if (!contract) {
    throw new Error(\`Unknown Axiom capability: \${capabilityKey}\`);
  }
  return contract;
}

export function assertDisclosureMode(capabilityKey: string, disclosureMode: string) {
  const contract = assertKnownCapability(capabilityKey);
  if (!contract.disclosureModes.includes(disclosureMode as never)) {
    throw new Error(\`Disclosure mode \${disclosureMode} is not declared for \${capabilityKey}\`);
  }
}

export const axiomApp = ${JSON.stringify(graph.app?.name || "unknown")};
`;
}

function reportMarkdown(graph, diagnostics, target) {
  const errors = diagnostics.filter((item) => item.severity === "error");
  const warnings = diagnostics.filter((item) => item.severity === "warning");
  const generatedContracts = policyMatrix(graph)
    .map(
      (item) => `### ${item.capability}

- Reads: ${item.reads.join(", ") || "none declared"}
- Disclosure: ${item.disclosureModes.join(", ") || "none declared"}
- Decisions: ${item.decisions.map((decision) => decision.kind).join(", ") || "none declared"}
- Approval path: ${item.approval ? "yes" : "no"}`,
    )
    .join("\n\n");

  return `# Axiom Verification Report

App: ${graph.app?.name || "unknown"}
Target: ${target}

## Summary

- Capabilities checked: ${graph.capabilities.length}
- Actors checked: ${graph.actors.length}
- Data classes checked: ${graph.dataClasses.length}
- Errors: ${errors.length}
- Warnings: ${warnings.length}

## Diagnostics

${diagnostics.length ? diagnostics.map((item) => `- **${item.severity.toUpperCase()}** ${item.message}${item.ref ? ` (${item.ref})` : ""}`).join("\n") : "- No diagnostics."}

## Generated Contracts

${generatedContracts}
`;
}

export function generateArtifacts(graph, diagnostics, { target }) {
  if (target !== "typescript") {
    throw new Error(`Unsupported target ${target}. The MVP currently supports only typescript.`);
  }

  return [
    { path: "policy-matrix.json", contents: `${stringify(policyMatrix(graph))}\n` },
    { path: "capabilities.ts", contents: capabilitiesTs(graph) },
    { path: "data-classes.ts", contents: dataClassesTs(graph) },
    { path: "audit-events.ts", contents: auditEventsTs(graph) },
    { path: "policy-evaluator.ts", contents: policyEvaluatorTs(graph) },
    { path: "policy-evaluator.mjs", contents: policyEvaluatorMjs(graph) },
    { path: "runtime-guards.ts", contents: runtimeGuardsTs(graph) },
    { path: "axiom-report.md", contents: reportMarkdown(graph, diagnostics, target) },
    {
      path: "README.md",
      contents: `# Generated Axiom Artifacts

These files were generated from an Axiom source graph.

- \`policy-matrix.json\`: capability, data, disclosure, policy, broker, and audit matrix
- \`capabilities.ts\`: generated capability contracts
- \`data-classes.ts\`: generated sensitive data class contracts
- \`audit-events.ts\`: generated audit obligations
- \`policy-evaluator.ts\`: generated deterministic policy evaluator
- \`policy-evaluator.mjs\`: generated deterministic policy evaluator for plain Node demos
- \`runtime-guards.ts\`: minimal TypeScript runtime assertions
- \`axiom-report.md\`: validation and generation report

Regenerate with:

\`\`\`bash
axiom generate <file.ax> --target typescript --out generated
\`\`\`
`,
    },
  ];
}
