import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { parseAxiom } from "./parser.mjs";
import { evaluateAxiomPolicy } from "./runtime.mjs";
import { loadSimulationExamples } from "./simulations.mjs";
import { validateGraph } from "./validator.mjs";

function stringify(value) {
  return JSON.stringify(value, null, 2);
}

function generatedNodeTest(graph, examples) {
  const cases = examples.map((example) => ({
    description: example.description,
    capability: example.capability,
    facts: example.facts,
    expectedDecision: example.expect?.decision || evaluateAxiomPolicy(graph, example.capability, example.facts).decision,
  }));

  const policyGraph = {
    capabilities: graph.capabilities.map((capability) => ({
      name: capability.name,
      sections: { approval: capability.sections.approval || [] },
      policy: capability.policy,
    })),
  };

  return `/* Generated by Axiom. Do not edit directly. */
import { describe, it } from "node:test";
import assert from "node:assert/strict";

const policyGraph = ${stringify(policyGraph)};
const cases = ${stringify(cases)};

const decisionOrder = ["deny", "require_approval", "allow"];

function normalizeFactValue(value) {
  if (value === true || value === "true") return true;
  if (value === false || value === "false") return false;
  return Boolean(value);
}

function normalizeCondition(condition) {
  return condition.replace(/^(and|or)\\s+/, "").trim();
}

function conditionKey(condition) {
  return normalizeCondition(condition)
    .replace(/^not\\s+/, "")
    .replace(/\\s+/g, "_");
}

function evaluateCondition(condition, facts) {
  const normalized = normalizeCondition(condition);
  const negated = normalized.startsWith("not ");
  const key = conditionKey(normalized);
  const value = normalizeFactValue(facts[key]);
  return negated ? !value : value;
}

function evaluateDecision(decision, facts) {
  if (!decision.conditions.length) return { matched: false, reasons: [] };

  let matched = evaluateCondition(decision.conditions[0], facts);
  const reasons = matched ? [conditionKey(decision.conditions[0])] : [];

  for (const condition of decision.conditions.slice(1)) {
    const operator = condition.startsWith("or ") ? "or" : "and";
    const conditionMatched = evaluateCondition(condition, facts);
    const key = conditionKey(condition);

    if (operator === "and") {
      matched = matched && conditionMatched;
      if (conditionMatched) reasons.push(key);
    } else {
      matched = matched || conditionMatched;
      if (conditionMatched) reasons.push(key);
    }
  }

  return { matched, reasons: [...new Set(reasons)] };
}

function evaluateAxiomPolicy(capabilityKey, facts = {}) {
  const capability = policyGraph.capabilities.find((item) => item.name === capabilityKey);

  if (!capability) {
    return { capability: capabilityKey, decision: "deny", reasons: ["unknown_capability"] };
  }

  for (const decisionKind of decisionOrder) {
    const decisions = capability.policy.decisions.filter((decision) => decision.kind === decisionKind);
    for (const decision of decisions) {
      const result = evaluateDecision(decision, facts);
      if (result.matched) {
        return { capability: capability.name, decision: decision.kind, reasons: result.reasons };
      }
    }
  }

  return { capability: capability.name, decision: "deny", reasons: ["no_policy_rule_matched"] };
}

describe("Axiom policy simulation examples", () => {
  cases.forEach((item, index) => {
    it(item.description || \`simulation example \${index + 1}\`, () => {
      const result = evaluateAxiomPolicy(item.capability, item.facts);
      assert.equal(result.decision, item.expectedDecision);
    });
  });
});
`;
}

export async function generateNodeTests(options = {}) {
  const appPath = resolve(options.appPath);
  const examplesPath = resolve(options.examplesPath);
  const outDir = resolve(options.outDir || "generated-tests");
  const target = options.target || "node";

  if (target !== "node") {
    throw new Error(`Unsupported test target ${target}. The MVP currently supports only node.`);
  }

  const source = await readFile(appPath, "utf8");
  const graph = parseAxiom(source, appPath);
  const diagnostics = validateGraph(graph);
  const errors = diagnostics.filter((item) => item.severity === "error");
  if (errors.length) {
    throw new Error(`Cannot generate tests because app.ax has ${errors.length} validation error(s).`);
  }

  const examples = await loadSimulationExamples(examplesPath);
  const testPath = join(outDir, "axiom-policy.test.mjs");
  await mkdir(dirname(testPath), { recursive: true });
  await writeFile(testPath, generatedNodeTest(graph, examples), "utf8");

  return { outDir, testPath, examples };
}
