# Generated by Axiom. Do not edit directly.
from dataclasses import dataclass


@dataclass(frozen=True)
class AxiomAuditObligation:
    capability: str
    audit: list[str]


AXIOM_AUDIT_OBLIGATIONS: list[AxiomAuditObligation] = [
    AxiomAuditObligation(**{
      "capability": "summarize_private_document",
      "audit": [
        "invocation",
        "policy_decision",
        "broker_execution",
        "disclosure_mode",
        "never log raw_document"
      ]
    }),
]


def audit_obligations_for(capability: str) -> list[str]:
    for obligation in AXIOM_AUDIT_OBLIGATIONS:
        if obligation.capability == capability:
            return obligation.audit
    return []
