# Generated by Axiom. Do not edit directly.
from typing import Any, Literal

from pydantic import BaseModel, Field


AxiomDecision = Literal["allow", "deny", "require_approval"]


class AxiomCapability(BaseModel):
    key: str
    purpose: list[str] = Field(default_factory=list)
    reads: list[str] = Field(default_factory=list)
    disclosure_modes: list[str] = Field(default_factory=list)
    forbidden_disclosure: list[str] = Field(default_factory=list)
    decisions: list[AxiomDecision] = Field(default_factory=list)


class AxiomDataClass(BaseModel):
    key: str
    sensitivity: str | None = None
    allowed_disclosure: list[str] = Field(default_factory=list)
    default_approval: list[str] = Field(default_factory=list)


class AxiomPolicyResult(BaseModel):
    capability: str
    decision: AxiomDecision
    reasons: list[str] = Field(default_factory=list)
    matched_rule: dict[str, Any] | None = None
    required_approval: dict[str, Any] | None = None


AXIOM_CAPABILITIES: list[AxiomCapability] = [
    AxiomCapability(**{
      "key": "summarize_private_document",
      "purpose": [
        "summarize one user-selected private document without exposing raw contents"
      ],
      "reads": [
        "private.document"
      ],
      "disclosure_modes": [
        "summary"
      ],
      "forbidden_disclosure": [
        "raw_document_export",
        "unrelated_document_fields"
      ],
      "decisions": [
        "allow",
        "require_approval",
        "deny"
      ]
    }),
]

AXIOM_DATA_CLASSES: list[AxiomDataClass] = [
    AxiomDataClass(**{
      "key": "private.document",
      "sensitivity": "high",
      "allowed_disclosure": [
        "summary",
        "task_fields"
      ],
      "default_approval": None
    }),
]
