# Generated by Axiom. Do not edit directly.
import re
from typing import Any, Literal, TypedDict


AxiomDecision = Literal["allow", "deny", "require_approval"]


class AxiomPolicyResult(TypedDict):
    capability: str
    decision: AxiomDecision
    reasons: list[str]
    matched_rule: dict[str, Any] | None
    required_approval: dict[str, Any] | None


AXIOM_POLICY_TABLE: list[dict[str, Any]] = [
  {
    "key": "summarize_private_document",
    "approval": [
      "one_time_default",
      "binds request_hash, owner_id, capability_key, destination_identity, expiry"
    ],
    "decisions": [
      {
        "kind": "allow",
        "conditions": [
          "owner_authenticated",
          "and document_selected",
          "and destination_local"
        ]
      },
      {
        "kind": "require_approval",
        "conditions": [
          "destination_external",
          "or summary_includes_sensitive_details"
        ]
      },
      {
        "kind": "deny",
        "conditions": [
          "schema_malformed",
          "or requests_raw_document",
          "or ownership_scope_invalid"
        ]
      }
    ]
  }
]


def _normalize_condition(condition: str) -> str:
    return re.sub(r"^(and|or)\s+", "", condition).strip()


def _condition_key(condition: str) -> str:
    normalized = _normalize_condition(condition)
    normalized = re.sub(r"^not\s+", "", normalized)
    return re.sub(r"\s+", "_", normalized)


def _condition_matches(condition: str, facts: dict[str, Any]) -> bool:
    normalized = _normalize_condition(condition)
    negated = normalized.startswith("not ")
    key = _condition_key(normalized)
    value = facts.get(key) is True or facts.get(key) == "true"
    return not value if negated else value


def _decision_matches(decision: dict[str, Any], facts: dict[str, Any]) -> tuple[bool, list[str]]:
    conditions = decision.get("conditions", [])
    if not conditions:
        return False, []

    matched = _condition_matches(conditions[0], facts)
    reasons = [_condition_key(conditions[0])] if matched else []

    for condition in conditions[1:]:
        operator = "or" if condition.startswith("or ") else "and"
        next_match = _condition_matches(condition, facts)
        if operator == "and":
            matched = matched and next_match
        else:
            matched = matched or next_match
        if next_match:
            reasons.append(_condition_key(condition))

    return matched, list(dict.fromkeys(reasons))


def evaluate_axiom_policy(capability_key: str, facts: dict[str, Any] | None = None) -> AxiomPolicyResult:
    facts = facts or {}
    contract = next((item for item in AXIOM_POLICY_TABLE if item["key"] == capability_key), None)
    if contract is None:
        return {
            "capability": capability_key,
            "decision": "deny",
            "reasons": ["unknown_capability"],
            "matched_rule": None,
            "required_approval": None,
        }

    for decision_kind in ["deny", "require_approval", "allow"]:
        for decision in [item for item in contract["decisions"] if item["kind"] == decision_kind]:
            matched, reasons = _decision_matches(decision, facts)
            if matched:
                return {
                    "capability": contract["key"],
                    "decision": decision["kind"],
                    "reasons": reasons,
                    "matched_rule": decision,
                    "required_approval": (
                        {"capability": contract["key"], "binds": contract["approval"]}
                        if decision["kind"] == "require_approval"
                        else None
                    ),
                }

    return {
        "capability": contract["key"],
        "decision": "deny",
        "reasons": ["no_policy_rule_matched"],
        "matched_rule": None,
        "required_approval": None,
    }
